INSERT INTO MARCAS (IDMARCA, NOMBRE, PAIS) VALUES (01, "Ford", "USA");
INSERT INTO MARCAS (IDMARCA, NOMBRE, PAIS) VALUES (02, "Chevrolet", "USA");
INSERT INTO MARCAS (IDMARCA, NOMBRE, PAIS) VALUES (03, "Dodge", "USA");
INSERT INTO MARCAS (IDMARCA, NOMBRE, PAIS) VALUES (04, "Honda", "JPN");
INSERT INTO MARCAS (IDMARCA, NOMBRE, PAIS) VALUES (05, "Nissan", "JPN");